export { default as PageNotFound } from "./PageNotFound";
export { default as LoginPage } from "./LoginPage";
export { default as CreatePassword } from "./CreatePassword";
export { default as Dashboard } from "./Dashboard";
export { default as Settings } from "./Settings";
export { default as Products } from "./Products";
export { default as Inventory } from "./Inventory";
export { default as Home } from "./Home";
export { default as Customers } from "./Customers";
